### ISSUE TITLE
Investigate / improvements around dealmaking errors and logging (for Docker Devnet dealmaking script)

### ISSUE THREAD

**Issue by brendalee** [filecoin-project/boost#1147]
[Dogfooding feedback] Investigate / improvements around dealmaking errors and logging

- random error notice during output while calculating commp, didn’t seem to be a problem but weird:
> `[flexi_logger][ERRCODE::Time] flexi_logger has to work with UTC rather than with local time, caused by IndeterminateOffset`

- “Press any key to show the file content” yielded
> `ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid bafk2bzacec3jst4tkh424chatp273o6rxvipfg54kphd56gaxobpcdtr2sgco: getting pieces containing block bafk2bzacec3jst4tkh424chatp273o6rxvipfg54kphd56gaxobpcdtr2sgco: failed to lookup index for mh a0e40220b6994f9351f9ae08e09bf5fdbbd1bd50f29bbc53ce3ef8c0bb82f10e71d48c27, err: datastore: key not found`

- This looks very familiar, we see this commonly in autoretrieve - how many different kinds of cases does this happen? It seems like this was a “not published” case, but are there others that autoretrieve would encounter (content is in the indexer already). If so, can we differentiate these more so it doesn’t always look like a blockstore error?

**Comment by jacobheun** [comment]
> This looks very familiar, we see this commonly in autoretrieve - how many different kinds of cases does this happen? It seems like this was a “not published” case, but are there others that autoretrieve would encounter (content is in the indexer already). If so, can we differentiate these more so it doesn’t always look like a blockstore error?

Yeah, this will happen until the deal gets into sealing and has been indexed. Improvements here _should_ land as part of the index lifecycle improvements we have on the short term roadmap - #1002 

> random error notice during output while calculating commp, didn’t seem to be a problem but weird
I'm assuming this was maybe an m1 user? As there isn't a problem for the user and it's for a docker build I think we can skip this for now unless it becomes a problem.


Given the above I am going to go ahead and close this since AIs are either wont fix, or is duplicated by planned effort.
