### ISSUE TITLE
Create API for deal acceptance in `boostd`

### ISSUE THREAD

**Issue by LexLuthr** [filecoin-project/boost#1261]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the Boost forum](https://github.com/filecoin-project/boost/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated feature request to propose.

### Boost component

- [X] boost daemon - storage providers
- [ ] boost client
- [ ] boost UI
- [ ] boost data-transfer
- [ ] boost index-provider
- [ ] Other

### What is the motivation behind this feature request? Is your feature request related to a problem? Please describe.

https://github.com/filecoin-project/boost/issues/1222#issuecomment-1456168842

This would be useful for folks who are onboarding large amounts of data to their own miner. It bypasses libp2p deal proposal.

### Describe the solution you'd like

Create a json-rpc to directly make deals with the daemon. API should be similar to dummydeal. We should account for logging these deals same as libp2p deals.

**Comment by beck-8** [comment]
> This would be useful for folks who are onboarding large amounts of data to their own miner. It bypasses libp2p deal proposal.
This is not self-dealing, mind you. The transaction received by an SP requires the client's signature, but usually the client's private key is not in the SP's possession.
I'm just here to say you not to lump them together, to prevent deviations in requirements.

The essential requirement is to provide an API to support the sending of transactions, rather than just using the command line.
