### ISSUE TITLE
16 EiB free storage space after decreasing MaxStagingDealsBytes 

### ISSUE THREAD

**Issue by web3-providers** [filecoin-project/boost#1297]
### Checklist

- [X] This is **not** a question or a support request. If you have any boost related questions, please ask in the [discussion forum](https://github.com/filecoin-project/boost/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/boost/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/boost/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/boost/issues) and the [discussion forum](https://github.com/filecoin-project/boost/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/boost/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to boost.

### Boost component

- [ ] boost daemon - storage providers
- [ ] boost client
- [X] boost UI
- [ ] boost data-transfer
- [ ] boost index-provider
- [ ] Other

### Boost Version

```text
boostd version 1.6.0+git.aced70f
```

### Describe the Bug

reducing the MaxStagingDealsBytes to from 1500000000000 to 750000000000 after boost did already accept incomming files up to 1.5TB   lead to this strange effect (Free Space  16 EiB ) : 
 
![image](https://user-images.githubusercontent.com/116538504/225912971-48af9b35-68cd-44f8-9d07-bc362d109076.png)

### Logging Information

```text
Non that I find related
```

### Repo Steps

1. Run '...'
2. Do '...'
3. See error '...'
...

**Comment by LexLuthr** [comment]
@jacobheun Can you please update your explanation of the bug here?

**Comment by jacobheun** [comment]
I believe the bug is in the calculation at https://github.com/filecoin-project/boost/blob/v1.6.1-rc1/storagemanager/storagemanager.go#L65. The tagged storage is over the new value set in the config, which is likely causing the uint overflow to come back as 16EiB. 

We should add a unit test around that and then just return 0 if the tagged amount is greater. This should only occur if the `MaxStagingDealsBytes` is set lower than currently tagged space, but you'll just keep accepting deals if space is the only potential limited in the deal filters.
