### ISSUE TITLE
Deal Status Protocol V2

### ISSUE THREAD

**Issue by dirkmc** [filecoin-project/boost#220]
For clients to know what the status of the deal is, we should implement the same Deal Status Protocol as go-fil-markets .

However, deal status V2 protocol should take in a dealUUID instead of the proposal cid and will get back a Boost checkpoint instead of the markets state.

**Comment by aarshkshah1992** [comment]
We can re-use existing deal status protocol and simply add a translation layer in Boost to map checkpoints to market states for the closed alpha milestone to facilitate faster testing.

For the alpha milestone, we'll implement Deal Status V2 that takes in a deal UUID instead of the legacy proposal cid and ask clients to upgrade.
