### ISSUE TITLE
Add Boost client CLI command to make a storage deal proposal

### ISSUE THREAD

**Issue by dirkmc** [filecoin-project/boost#278]
Add a Boost client CLI command that can be used to make a storage deal proposal.

The command should have parameters for
- source url
- commp
- car file size

eg `boost propose-deal --provider=f1... --source="https://example.com/example.car" --size=12345 --commp=bafysgj23gadsf3423sdgkn43`

**Comment by xinaxu** [comment]
We will be working on integrating with boost client CLI to make deals with storage providers. In addtion to the parameters above, we also need to support
1. --verified
2. --from -> the client wallet address to send the wallet from
3. --duration -> the duration of the deal
4. --start-epoch -> start date of the deal
5. [optional] --fast-retrieval -> whether to keep unsealed copy
proposal_cid needs to be returned, so that we can find the deal id once the storage provider publishes the deal.

**Comment by Fatman13** [comment]
What's the difference between making deals using boost and lotus client? Is it basically the same?

**Comment by nonsense** [comment]
@Fatman13 the end result is technically the same, but the process is different.

Lotus is using protocol v1.1.0, whereas Boost is using protocol v1.2.0

```
const DealProtocolv110 = "/fil/storage/mk/1.1.0"
const DealProtocolv120 = "/fil/storage/mk/1.2.0"
```

Online deal data could also be transferred with a different protocol because of this.

**Comment by dirkmc** [comment]
@Fatman13 in particular protocol v1.2.0 allows transfer with HTTP. So the client can send the url of an HTTP server in the deal proposal, and Boost will download the CAR file from the server over HTTP.

**Comment by nonsense** [comment]
We'll add the following 2 flags on the next iteration.

```
--private-key -> specify the private key of the wallet to sign the message so that we don't need to store the wallet private key with some lotus node. The idea is to allow boost CLI to utilize public lotus node such as Glif to accomplish dealmaking rather than requiring the client to install and run a local lotus daemon. This is particulaly critical to attract smaller clients such as someone wants to store a small file on Filecoin network without a modern hardware to run lotus. Lite node may also work.
--fast-retrieval -> whether to keep unsealed copy
```

**Comment by xinaxu** [comment]
Awesome!
