### ISSUE TITLE
Feat Req: Add Filtering to Deal Sections in UI

### ISSUE THREAD

**Issue by marshyonline** [filecoin-project/boost#617]
Being able to filter the lists of deals(including legacy deals) in the UI could be super helpful for finding stuck deals in particular states or deals from a specific client.

**Comment by dirkmc** [comment]
You can filter the list of deals using the search box at the top right of the Storage Deals page:

<img width="1140" alt="Screen Shot 2022-06-27 at 9 38 08 AM" src="https://user-images.githubusercontent.com/169124/175885850-115292ca-74d7-4f02-ba12-a150cdff819a.png">

Note that you can copy and paste the client's peer ID into this box to filter for a particular client.

For legacy deals it's not straight-forward to implement this functionality because of the data format that is used when making legacy deals.
