### ISSUE TITLE
booster-bitswap block filter

### ISSUE THREAD

**Issue by dirkmc** [filecoin-project/boost#731]
Add a mechanism by which booster-bitswap can deny requests for a cid.

For example
- bitswap client requests cid `abcd` (either `want-have` or `want-block`)
- booster-bitswap calls filter with `abcd` as a parameter and receives `true` / `false` response
- if `true` bitswap server returns the block
- if `false` bitswap server returns `DONT_HAVE`

Examples of filter mechanisms:
- a script that takes the cid as a parameter and returns an exit code of `0` or `1`
- an http endpoint that takes the cid as a parameter and returns `200` or `404`

We should experiment with these filter mechanisms to see what is most intuitive and performant.

The filter should use the [`WithPeerBlockRequestFilter` hook](https://github.com/ipfs/go-bitswap/blob/4e3736a773545bf09d5178a2be24043b76560f87/server/internal/decision/engine.go#L223) to approve / deny requests for a block.

**Comment by LaurenSpiegel** [comment]
1) bitscreen hooks into the lotus config so should still be picked up by boost -- https://github.com/Murmuration-Labs/bitscreen-cli/blob/main/bitscreen_cli/commands/setup.py#L89

BUT...is the place/way it filters compatible with how we would call a filter function for bitswap?

2) It looks like bitscreen is doing a linear lookup for each CID request if I am reading correctly and the file read process is what is usually used -- https://github.com/Murmuration-Labs/bitscreen/blob/master/bitscreen.go#L132

or just lookup in set if using the server (preferable since has updates) -- https://github.com/Murmuration-Labs/bitscreen-updater/blob/master/bitscreen_updater/__main__.py#L75 

We should test out hitting it and see how performance is impacted. 

-----
If bitscreen is not a good fit, we can
1) ask the bitscreen team to modify
2) simply set up a client that can hit a server holding the badbits (https://badbits.dwebops.pub/) or other deny list and returns whether to filter or not. 

As a next step it might make sense to set up a joint call to have the bitscreen team walk us through how it is supposed to work and any limitations/issues we should be aware of.

cc @brendalee

**Comment by willscott** [comment]
this is also relevant for booster-http https://github.com/filecoin-project/boost/pull/946

Should each edge retrieval process call filters / enforce policy, or should it happen at the centralized call to the piece metastore `pieceMeta.BlockstoreGet(ctx, blockCid)`?

**Comment by jacobheun** [comment]
This issue should be resolved via https://github.com/filecoin-project/boost/pull/825 correct @dirkmc ?

**Comment by dirkmc** [comment]
Yes, closing
