### ISSUE TITLE
web ui: link from deals page to legacy deals page

### ISSUE THREAD

**Issue by dirkmc** [filecoin-project/boost#848]
Currently the only way to get to the legacy deals page is by clicking on a small link in the menu:
<img width="239" alt="Screen Shot 2022-09-30 at 11 07 52 AM" src="https://user-images.githubusercontent.com/169124/193235798-29ecaa06-1513-4139-b5b5-6405e282996c.png">

If there is at least one legacy deal, show a link at the top of the Deals page to the Legacy Deals page.

**Comment by RobQuistNL** [comment]
That is _not_ good UI design :sweat_smile: ;

- Those entire "blocks" show a 'pointer' cursor (which tells me the entire block is just a link)
- There's no hovering line effects nor a line under it.
- The legacy deals can take 20 seconds to show up (otherwise it just shows nothing)
- It was just the hovering and my cursor change that told me that each left item is actually a button.

![image](https://user-images.githubusercontent.com/1442796/193267548-c0177dac-ca1e-4e51-8f55-84bc493a2d65.png)

**Comment by dirkmc** [comment]
Closed by https://github.com/filecoin-project/boost/pull/851
